#include <iostream>
#include <vector>
#include <algorithm>

using namespace std;


void generatePermutations(vector<int>&nums, int index, vector<vector<int>>& ans)
{
    //Approach 2: Intuition is to pick every element for cur position and then call rec to pick all the remaining elements for the next position once.
        //T.C --> O((loop running)N * N! [permutations being generated]) ~ O(N*N!) 
        //S.C --> No extra space is being used as all the permutations are generated by in place swapping of elements.
    if(index == nums.size())
    {
        ans.push_back(nums);
        return;
    }

    for(int i = index; i < nums.size(); i++)
    {
        swap(nums[i], nums[index]);
        generatePermutations(nums, index+1, ans);
        swap(nums[i], nums[index]);
    }
}

vector<vector<int>> permute(vector<int>&nums)
{
    vector<vector<int>> ans;

    generatePermutations(nums, 0, ans);

    return ans;
}

int main()
{
    vector<int> nums = {1,2,3,4};

    vector<vector<int>> ans = permute(nums);
    for(auto it: ans)
    {
        for(auto i: it)
        {
            cout<<i<<" ";
        }
        cout<<endl;
    }

    return 0;
}